# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHbhhH9II9J_tmvTOtvCZrajQQfagrID
"""

!unzip data.zip

import pandas as pd
import numpy as np
import glob
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, RepeatVector, TimeDistributed, Dense

file_list = glob.glob('*.parquet')
df = pd.concat([pd.read_parquet(f) for f in file_list])

scaler = MinMaxScaler()
temp_data = df[['temperature']].values
scaled_data = scaler.fit_transform(temp_data)

def create_sequences(data, seq_length):
    sequences = []
    for i in range(len(data) - seq_length):
        window = data[i:(i + seq_length)]
        sequences.append(window)
    return np.array(sequences)

SEQUENCE_LENGTH = 10
X_train = create_sequences(scaled_data, SEQUENCE_LENGTH)

model = Sequential()
model.add(LSTM(16, activation='relu', input_shape=(SEQUENCE_LENGTH, 1), return_sequences=False))
model.add(RepeatVector(SEQUENCE_LENGTH))
model.add(LSTM(16, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))

model.compile(optimizer='adam', loss='mse')

print("Starting training...")
history = model.fit(
    X_train, X_train,
    epochs=50,
    batch_size=16,
    validation_split=0.1
)
print(f"Final Training Loss: {history.history['loss'][-1]:.4f}")

predictions = model.predict(X_train)
errors = np.mean(np.square(X_train - predictions), axis=(1, 2))
print(f"Average Error: {np.mean(errors):.4f}")
print(f"Maximum Error: {np.max(errors):.4f}")

THRESHOLD=np.percentile(errors,95)
print(f"Threshold: {THRESHOLD:.4f}")

anomalies=errors>THRESHOLD
num_anomalies=np.sum(anomalies)

print(f"Total sequence analyses: {len(errors)}")
print(f"Anomalies Detected (alarm trigger): {(num_anomalies)}")

model.save("anomaly_model.keras")
print("Model saved successfully as 'anomaly_model.keras'")

import joblib
joblib.dump(scaler, 'scaler.gz')
print("Scaler saved successfully as 'scaler.gz'")

